apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mynameisingress
spec:
  rules:
  - host: yourhostname
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: http
