apiVersion: v1
kind: ReplicationController
metadata:
  name: mnginx
spec:
  replicas: 1
  selector:
    app: malabel
  template:
    metadata:
      name: jupyter
      labels:
        app: malabel
    spec:
      containers:
        - name: jupyter
          image: skippbox/jupyter:0.0.3
          ports:
          - containerPort: 8888
            protocol: TCP
            name: http


